
instituciones_data = [
    {
        "nombre": "Instituto de Meteorología de Cuba",
        "descripcion": "La Misión principal del Instituto de Meteorología es suministrar información meteorológica y climática autorizada, confiable y oportuna sobre el estado y comportamiento futuro de la atmósfera. Esta información está dirigida a velar por la seguridad de la vida humana y a reducir las pérdidas de bienes materiales ante desastres naturales de origen meteorológico, contribuyendo directamente al bienestar de la comunidad y al desarrollo sostenible.",
        "direccion": "4MV4+PQQ, La Habana, Cuba",
    },
    {
        "nombre": "Instituto de Geología y Paleontología de Cuba",
        "descripcion": "El actual Instituto de Geología y Paleontología (IGP) es el resultado de diversos cambios estructurales e institucionales ocurridos desde 1967 hasta hoy.",
        "direccion": "Vía Blanca No. 1002 e/ Línea del Ferrocarril y Ctra. Central, San Miguel del Padrón, La Habana",
    },
    {
        "nombre": "Instituto Superior de Tecnologías y Ciencias Aplicadas",
        "descripcion": "Esta licenciatura se estudia en el Instituto Superior de Tecnologías y Ciencias Aplicadas de la Universidad de La Habana, ubicado en la Quinta de los Molinos, en el municipio Plaza de la Revolución. Consta de un plan de estudios de 4 años esbozado con disciplinas de ciencias básicas y especializadas y un grupo de optativas y electivas. Las asignaturas básicas comprenden ramas de la matemática, la física, la química y la programación, mientras que las asociadas directamente a la carrera están centradas en los componentes de la meteorología como: radar, satélite, sinóptica, mesoescala, marina y física de las nubes.",
        "direccion": "San Lázaro y L, Vedado. Ciudad de La Habana",
    },
]

departamentos_data = [
    {
        "nombre": "Física de la Atmósfera",
        "descripcion": "",
    },
    {
        "nombre": "Pronósticos",
        "descripcion": "",
    },
    {
        "nombre": "Radares",
        "descripcion": "",
    },
    {
        "nombre": "Recursos Humanos",
        "descripcion": "",
    },
    {
        "nombre": "Dirección",
        "descripcion": "",
    },
    {
        "nombre": "Meteorología",
        "descripcion": "",
    },
]

nivel_academico_data = [
    {
        "nivel_academico": "Técnico",
        "descripcion": "",
    },
    {
        "nivel_academico": "Licenciado",
        "descripcion": "",
    },
    {
        "nivel_academico": "Ingeniero",
        "descripcion": "",
    },
    {
        "nivel_academico": "Master",
        "descripcion": "",
    },
    {
        "nivel_academico": "Doctor",
        "descripcion": "",
    },
    {
        "nivel_academico": "Estudiante Universitario",
        "descripcion": "",
    },
]

especializacion_data = [
    {
        "especializacion": "Informático",
        "descripcion": "",
    },
    {
        "especializacion": "Físico",
        "descripcion": "",
    },
    {
        "especializacion": "Meteorólogo",
        "descripcion": "",
    },
    {
        "especializacion": "Cibernético",
        "descripcion": "",
    },
    {
        "especializacion": "Químico",
        "descripcion": "",
    },
    {
        "especializacion": "Eléctrico",
        "descripcion": "",
    },
    {
        "especializacion": "Telecomunicador",
        "descripcion": "",
    },
]

investigaciones_data = [
    {
        "nombre": "Estudio de tormentas eléctricas",
        "descripcion": "Se necesita realizar un estudio de las tormentas electricas en distintos lugares de la Ciudad de la Habana",
        "fecha_comienzo": "2022-05-03 08:30:00",
        "fecha_culminacion": None,
        "completado": 45,
        "trabajador1": "Marvin",
        "trabajador2": "Gabriela",
        "trabajador3": "Alex",
    },
    {
        "nombre": "Sistema de predicción de tornados",
        "descripcion": "Se pretende crear un sistema con una metodología para la predicción a tiempo de manera precisa de tornados. Es importante adquirir conocimientos de los Instituto de Estdos Unidos que cuentan con una amplia experiencia en este campo",
        "fecha_comienzo": "2022-07-05 09:30:00",
        "fecha_culminacion": None,
        "completado": 20,
        "trabajador1": "Marvin",
        "trabajador2": "Jose Luis",
        "trabajador3": None,
    },
    {
        "nombre": "Penetraciones del mar en oriente",
        "descripcion": "Durante años se han visto cambios importante en las penetraciones del mar en la región oriental del país, estos cambio reponden a un patron el cual es de interes para esta investigación",
        "fecha_comienzo": "2023-05-05 08:30:00",
        "fecha_culminacion": None,
        "completado": 2,
        "trabajador1": "Mabel",
        "trabajador2": "Gabriela",
        "trabajador3": None,
    },
    {
        "nombre": "Sequía en la región central",
        "descripcion": "La región central del país siempre a padecido de intensas sequía durante los meses de verano, en los ultimos años estas se han incrementado",
        "fecha_comienzo": "2021-02-12 11:30:00",
        "fecha_culminacion": None,
        "completado": 95,
        "trabajador1": "Marvin",
        "trabajador2": "Gabriela",
        "trabajador3": "Alex",
    },
    {
        "nombre": "Integración de red de radares",
        "descripcion": "La red de radares necesita una actualización de la metodología de integración con la que se trabaja",
        "fecha_comienzo": "2022-06-04 09:30:00",
        "fecha_culminacion": "2023-04-04 09:30:00",
        "completado": 100,
        "trabajador1": "Marvin",
        "trabajador2": "Hendrix",
        "trabajador3": "Alex",
    },
    {
        "nombre": "Software para generación de pronósticos más precisos",
        "descripcion": "Dado que la mayoría de los software potentes que se usan para las mediciones y generaciones de pronósticos son de pago se hace necesario la creación con nuestros recursos de uno propio",
        "fecha_comienzo": "2023-01-03 08:30:00",
        "fecha_culminacion": None,
        "completado": 20,
        "trabajador1": "Bryan",
        "trabajador2": "Gabriela",
        "trabajador3": "Marvin",
    },
]

trabajador_data = [
    {
        "nombre": "Marvin",
        "apellidos": "Urías Moltó",
        "ci": "91050222289",
        "sexo": "masculino",
        "horas_ocupadas": 0,
        "institucion": "Instituto de Meteorología de Cuba",
        "departamento": "Física de la Atmósfera",
        "nivel_academico": "Ingeniero",
        "especializacion": "Informático",
        "usuario": 'marvin',
    },
    {
        "nombre": "Gabriela",
        "apellidos": "Lorenzo Gonzalez",
        "ci": "96010756584",
        "sexo": "femenino",
        "horas_ocupadas": 0,
        "institucion": "Instituto de Meteorología de Cuba",
        "departamento": "Radares",
        "nivel_academico": "Licenciado",
        "especializacion": "Físico",
        "usuario": 'gaby',
    },
    {
        "nombre": "Bryan",
        "apellidos": "Tylor Reberon",
        "ci": "91080625865",
        "sexo": "masculino",
        "horas_ocupadas": 0,
        "institucion": "Instituto de Meteorología de Cuba",
        "departamento": "Física de la Atmósfera",
        "nivel_academico": "Ingeniero",
        "especializacion": "Físico",
        "usuario": 'bryan',
    },
    {
        "nombre": "Jose Luis",
        "apellidos": "Gonzalez Muños",
        "ci": "91100258456",
        "sexo": "masculino",
        "horas_ocupadas": 0,
        "institucion": "Instituto de Geología y Paleontología de Cuba",
        "departamento": "Dirección",
        "nivel_academico": "Ingeniero",
        "especializacion": "Químico",
        "usuario": 'jose',
    },
    {
        "nombre": "Mabel",
        "apellidos": "Morales Otero",
        "ci": "91091821568",
        "sexo": "femenino",
        "horas_ocupadas": 0,
        "institucion": "Instituto Superior de Tecnologías y Ciencias Aplicadas",
        "departamento": "Meteorología",
        "nivel_academico": "Estudiante Universitario",
        "especializacion": "Meteorólogo",
        "usuario": 'mabe',
    },
    {
        "nombre": "Alex",
        "apellidos": "Cima de Villa",
        "ci": "91062078548",
        "sexo": "masculino",
        "horas_ocupadas": 0,
        "institucion": "Instituto de Meteorología de Cuba",
        "departamento": "Física de la Atmósfera",
        "nivel_academico": "Ingeniero",
        "especializacion": "Telecomunicador",
        "usuario": 'alex',
    },
    {
        "nombre": "Hendrix",
        "apellidos": "Cruz Hidalgo",
        "ci": "91021596314",
        "sexo": "masculino",
        "horas_ocupadas": 0,
        "institucion": "Instituto de Meteorología de Cuba",
        "departamento": "Radares",
        "nivel_academico": "Ingeniero",
        "especializacion": "Eléctrico",
        "usuario": 'hendrix',
    },
]

# parte_de_horas_data = [
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
#     {
#         "descripcion": "",
#         "fecha": "",
#         "horas_dedicadas": "",
#     },
# ]

tarea_data = [
    {
        "nombre": "Medición de carga eléctrica",
        "horas_necesarias": 20,
        "descripcion": "Se necesita medir la carga eléctrica en puntos especificos",
        "fecha_comienzo": "2022-05-06 08:30:00",
        "fecha_culminacion": None,
        "investigacion": 'Estudio de tormentas eléctricas',
        "trabajador1": "Marvin",
        "trabajador2": "Gabriela",
    },
    {
        "nombre": "Verificación de pararayos",
        "horas_necesarias": 45,
        "descripcion": "Se deben comprobar los pararayos en las zonas establecidas para el estudio",
        "fecha_comienzo": "2022-07-15 10:30:00",
        "fecha_culminacion": None,
        "investigacion": 'Estudio de tormentas eléctricas',
        "trabajador1": "Marvin",
        "trabajador2": None,
    },
    {
        "nombre": "Diferensiación del viento",
        "horas_necesarias": 15,
        "descripcion": "Estimar la diferencia de los viento y los cambios repentinos próximos a la ocurrencia de un tornado",
        "fecha_comienzo": "2022-07-05 10:30:00",
        "fecha_culminacion": None,
        "investigacion": 'Sistema de predicción de tornados',
        "trabajador1": None,
        "trabajador2": "Jose Luis",
    },
    {
        "nombre": "Estudio de atmósfera",
        "horas_necesarias": 25,
        "descripcion": "Estudiar el comportamiento atmosférico en la ocurrencia de un tornado",
        "fecha_comienzo": "2022-08-20 14:30:00",
        "fecha_culminacion": None,
        "investigacion": 'Sistema de predicción de tornados',
        "trabajador1": "Jose Luis",
        "trabajador2": "Marvin",
    },
    {
        "nombre": "Velocidad de máxima vientos",
        "horas_necesarias": 10,
        "descripcion": "Medir las velocidades máximas de los vientos durante un tornado y comparar con los datos de estudios internacionales",
        "fecha_comienzo": "2022-10-01 09:30:00",
        "fecha_culminacion": None,
        "investigacion": 'Sistema de predicción de tornados',
        "trabajador1": "Marvin",
        "trabajador2": None,
    },
    {
        "nombre": "Distancia de penetración",
        "horas_necesarias": 10,
        "descripcion": "Medir los patrones de distancias de penetración del mar en la región oriental de país",
        "fecha_comienzo": "2023-05-07 08:30:00",
        "fecha_culminacion": None,
        "investigacion": 'Penetraciones del mar en oriente',
        "trabajador1": None,
        "trabajador2": "Gabriela",
    },
    {
        "nombre": "Altura de las olas",
        "horas_necesarias": 10,
        "descripcion": "Calcular la altura de las olas duraste la ocurrencia de penetración del mar",
        "fecha_comienzo": "2023-05-07 10:30:00",
        "fecha_culminacion": None,
        "investigacion": 'Penetraciones del mar en oriente',
        "trabajador1": "Mabel",
        "trabajador2": "Gabriela",
    },
    {
        "nombre": "Intensidad de lluvias",
        "horas_necesarias": 30,
        "descripcion": "Llevar un registro de la intensidad de lluvias durante el verano en la región central del país",
        "fecha_comienzo": "2021-02-13 08:30:00",
        "fecha_culminacion": None,
        "investigacion": 'Sequía en la región central',
        "trabajador1": "Gabriela",
        "trabajador2": "Alex",
    },
    {
        "nombre": "Acumulación de agua",
        "horas_necesarias": 35,
        "descripcion": "Monitorear la acumulación de agua en la región central y comparar con años anteriores",
        "fecha_comienzo": "2021-04-25 08:30:00",
        "fecha_culminacion": None,
        "investigacion": 'Sequía en la región central',
        "trabajador1": "Gabriela",
        "trabajador2": "Alex",
    },
    {
        "nombre": "Rehacer método de conexión digital",
        "horas_necesarias": 45,
        "descripcion": "Rehacer el método a traves de software con  que se conecta la red de radares del Cuba",
        "fecha_comienzo": "2022-06-06 08:30:00",
        "fecha_culminacion": "2022-08-15 09:30:00",
        "investigacion": 'Integración de red de radares',
        "trabajador1": "Marvin",
        "trabajador2": "Hendrix",
    },
    {
        "nombre": "Automatizar salva de datos de radares",
        "horas_necesarias": 50,
        "descripcion": "Crear un software para manejar de forma automática la salva de los datos tomados por el radar",
        "fecha_comienzo": "2022-07-01 09:30:00",
        "fecha_culminacion": "2022-09-10 12:30:00",
        "investigacion": 'Integración de red de radares',
        "trabajador1": "Marvin",
        "trabajador2": "Hendrix",
    },
    {
        "nombre": "Crear interprete de modelos",
        "horas_necesarias": 30,
        "descripcion": "Se debe crear un interprete usando python que logre traducir los datos descargados de los modelos de medición",
        "fecha_comienzo": "2023-01-10 10:30:00",
        "fecha_culminacion": None,
        "investigacion": 'Software para generación de pronósticos más precisos',
        "trabajador1": "Bryan",
        "trabajador2": "Gabriela",
    },
    {
        "nombre": "Gestor de formulas",
        "horas_necesarias": 60,
        "descripcion": "Crear una app para gestionar las formulas con las que se realizaran las estimaciones a partir de las variable de los modelos",
        "fecha_comienzo": "2023-02-03 08:30:00",
        "fecha_culminacion": None,
        "investigacion": 'Software para generación de pronósticos más precisos',
        "trabajador1": "Bryan",
        "trabajador2": "Marvin",
    },
    {
        "nombre": "Generación de gráficos",
        "horas_necesarias": 50,
        "descripcion": "Crear un software con interfaz gráfica donde se generen gráficos con los datos de los diversos resultados",
        "fecha_comienzo": "2023-01-30 09:30:00",
        "fecha_culminacion": None,
        "investigacion": 'Software para generación de pronósticos más precisos',
        "trabajador1": "Bryan",
        "trabajador2": None,
    },
]


usuarios_data = [
    {
        "username": "marvin",
        "password": "123",
    },
    {
        "username": "gaby",
        "password": "123",
    },
    {
        "username": "bryan",
        "password": "123",
    },
    {
        "username": "jose",
        "password": "123",
    },
    {
        "username": "mabe",
        "password": "123",
    },
    {
        "username": "alex",
        "password": "123",
    },
    {
        "username": "hendrix",
        "password": "123",
    },
]