# Generated by Django 3.0.8 on 2022-08-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0007_object_pk_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'crear'), (1, 'actualizar'), (2, 'borrar')], verbose_name='action'),
        ),
    ]
