# Generated by Django 4.1.3 on 2023-02-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especializacion',
            name='nombre',
        ),
        migrations.AddField(
            model_name='especializacion',
            name='especializacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Especialización'),
        ),
    ]
