# Generated by Django 4.1.3 on 2023-02-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_remove_especializacion_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especializacion',
            name='especializacion',
            field=models.CharField(max_length=50, verbose_name='Especialización'),
        ),
    ]


