# Generated by Django 4.1.3 on 2023-06-07 01:04

from django.db import migrations
from Gestor.populate_data import *


def populate_data(apps, schema_editor):
    popualte_nomencladores()
    populate_trabajadores()
    populate_investigaciones()
    populate_tareas()
    populate_horas_ocupadas()


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_especializacion_especializacion'),
    ]

    operations = [
        migrations.RunPython(populate_data),
    ]
